/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-15 11:42:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.DecimalFormat;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.text.DecimalFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Full Trade Support - Manager Dashboard</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\" media=\"print\" onload=\"this.media='all'\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" rel=\"stylesheet\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/fontawesome.min.css\" rel=\"stylesheet\" media=\"print\" onload=\"this.media='all'\">\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { display: flex; min-height: 100vh; overflow-x: hidden; }\r\n");
      out.write("        .sidebar { width: 250px; background-color: #001f3f; color: #fff; flex-shrink: 0; padding-top: 1rem; }\r\n");
      out.write("        .sidebar a { display: block; padding: 12px 20px; color: #fff; text-decoration: none; transition: background 0.3s; }\r\n");
      out.write("        .sidebar a:hover { background-color: #003366; }\r\n");
      out.write("        .sidebar h5 { text-align: center; margin-bottom: 1rem; font-weight: bold; }\r\n");
      out.write("        .main-content { flex-grow: 1; background: #f8f9fa; }\r\n");
      out.write("        .navbar { background-color: #ffffff; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }\r\n");
      out.write("        .dashboard-content { padding: 2rem; }\r\n");
      out.write("        .custom-header { background-color: #0d0b56; color: white; }\r\n");
      out.write("        .btn-primary { background-color: #0d0b56; border-color: #0d0b56; }\r\n");
      out.write("        .btn-primary:hover { background-color: #003366; border-color: #003366; }\r\n");
      out.write("        .card { border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }\r\n");
      out.write("        .chart-container { max-width: 600px; margin: auto; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");
 String userRole = (String) session.getAttribute("userRole"); 
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"sidebar\">\r\n");
      out.write("        <h5 class=\"text-center fw-bold\">\r\n");
      out.write("            ");
      out.print( userRole != null ? userRole + " Panel" : "Panel" );
      out.write("\r\n");
      out.write("        </h5>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        ");
 if ("Cashier".equals(userRole)) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("            \r\n");
      out.write("             <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cashier\">\r\n");
      out.write("           		 <i class=\"fas fa-cash-register me-2\"></i> Cashier\r\n");
      out.write("        	</a>\r\n");
      out.write("            \r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 if ( "Stock Manager".equals(userRole)) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("            \r\n");
      out.write("             <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cashier\">\r\n");
      out.write("            <i class=\"fas fa-cash-register me-2\"></i> Cashier\r\n");
      out.write("        	</a>\r\n");
      out.write("            \r\n");
      out.write("             <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order-management\">\r\n");
      out.write("                <i class=\"fas fa-shopping-cart me-2\"></i> Order Management\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/item-list\">\r\n");
      out.write("                <i class=\"fas fa-box me-2\"></i> Item Management\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("    \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 if ( "Admin".equals(userRole)) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("            \r\n");
      out.write("             <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cashier\">\r\n");
      out.write("            <i class=\"fas fa-cash-register me-2\"></i> Cashier\r\n");
      out.write("        	</a>\r\n");
      out.write("            \r\n");
      out.write("             <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order-management\">\r\n");
      out.write("                <i class=\"fas fa-shopping-cart me-2\"></i> Order Management\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/item-list\">\r\n");
      out.write("                <i class=\"fas fa-box me-2\"></i> Item Management\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/supplier-list\">\r\n");
      out.write("                <i class=\"fas fa-truck me-2\"></i> Supplier Management\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/GetAllServlet\">\r\n");
      out.write("                <i class=\"fas fa-users me-2\"></i> User Management\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 if ( "Manager".equals(userRole)) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\">\r\n");
      out.write("                <i class=\"fas fa-chart-line me-2\"></i> Dashboard\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("             <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cashier\">\r\n");
      out.write("            <i class=\"fas fa-cash-register me-2\"></i> Cashier\r\n");
      out.write("        	</a>\r\n");
      out.write("            \r\n");
      out.write("             <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order-management\">\r\n");
      out.write("                <i class=\"fas fa-shopping-cart me-2\"></i> Order Management\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/item-list\">\r\n");
      out.write("                <i class=\"fas fa-box me-2\"></i> Item Management\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/supplier-list\">\r\n");
      out.write("                <i class=\"fas fa-truck me-2\"></i> Supplier Management\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/GetAllServlet\">\r\n");
      out.write("                <i class=\"fas fa-users me-2\"></i> User Management\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <a href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#settingsMenu\">\r\n");
      out.write("            <i class=\"fas fa-gear me-2\"></i> Settings\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"collapse ms-3\" id=\"settingsMenu\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile.jsp\" class=\"d-block mt-1\">\r\n");
      out.write("                <i class=\"fas fa-sliders-h me-2\"></i> Profile\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-content w-100\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-white px-4 shadow-sm\">\r\n");
      out.write("            <a class=\"navbar-brand fw-bold\" href=\"#\">Autoparts Pvt Ltd</a>\r\n");
      out.write("            <div class=\"ms-auto d-flex align-items-center\">\r\n");
      out.write("                ");
      out.print( session.getAttribute("Name") != null ? session.getAttribute("Name") : "Guest" );
      out.write("\r\n");
      out.write("                <div class=\"dropdown ms-3\">\r\n");
      out.write("                    <a class=\"btn btn-light dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"fas fa-user-circle fa-lg\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile.jsp\"><i class=\"fas fa-id-badge me-2\"></i> Profile</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\"><i class=\"fas fa-sign-out-alt me-2\"></i> Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"dashboard-content\">\r\n");
      out.write("            <h2 class=\"mb-4\">Manager Dashboard</h2>\r\n");
      out.write("            ");
 String error = (String) request.getAttribute("error"); if (error != null) { 
      out.write("\r\n");
      out.write("                <div class=\"alert alert-danger\">");
      out.print( error );
      out.write("</div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <div class=\"row mb-4\">\r\n");
      out.write("                <div class=\"col-md-4\"><div class=\"card p-3\"><h5>Total Orders</h5><p class=\"text-2xl font-bold text-[#0d0b56]\">\r\n");
      out.write("                    ");
      out.print( request.getAttribute("totalOrders") != null ? request.getAttribute("totalOrders") : 0 );
      out.write("</p></div></div>\r\n");
      out.write("                <div class=\"col-md-4\"><div class=\"card p-3\"><h5>Total Customers</h5><p class=\"text-2xl font-bold text-[#0d0b56]\">\r\n");
      out.write("                    ");
      out.print( request.getAttribute("totalCustomers") != null ? request.getAttribute("totalCustomers") : 0 );
      out.write("</p></div></div>\r\n");
      out.write("                <div class=\"col-md-4\"><div class=\"card p-3\"><h5>Total Revenue</h5><p class=\"text-2xl font-bold text-[#0d0b56]\">\r\n");
      out.write("                    $");
      out.print( request.getAttribute("totalRevenue") != null ? new DecimalFormat("#,##0.00").format(request.getAttribute("totalRevenue")) : "0.00" );
      out.write("</p></div></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mb-4\">\r\n");
      out.write("                <div class=\"col-md-12\"><div class=\"card p-3\"><h5>Annual Profit (Current Year)</h5><p class=\"text-2xl font-bold text-[#0d0b56]\">\r\n");
      out.write("                    $");
      out.print( request.getAttribute("annualProfit") != null ? new DecimalFormat("#,##0.00").format(request.getAttribute("annualProfit")) : "0.00" );
      out.write("</p></div></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card p-3\"><h5>Monthly Order Count</h5>\r\n");
      out.write("                        <div class=\"chart-container\"><canvas id=\"orderChart\"></canvas></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card p-3\"><h5>Monthly Profit</h5>\r\n");
      out.write("                        <div class=\"chart-container\"><canvas id=\"profitChart\"></canvas></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            const orderData = {\r\n");
      out.write("                labels: [\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"],\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    label: 'Orders',\r\n");
      out.write("                    data: [");
 Map<String, Integer> moc = (Map<String, Integer>) request.getAttribute("monthlyOrderCount"); for (String m : new String[]{"January","February","March","April","May","June","July","August","September","October","November","December"}) { out.print(moc != null ? moc.getOrDefault(m, 0) : 0); out.print(","); } 
      out.write("],\r\n");
      out.write("                    backgroundColor: '#0d0b56',\r\n");
      out.write("                    borderColor: '#0d0b56',\r\n");
      out.write("                    borderWidth: 1\r\n");
      out.write("                }]\r\n");
      out.write("            };\r\n");
      out.write("            new Chart(document.getElementById('orderChart'), {\r\n");
      out.write("                type: 'bar',\r\n");
      out.write("                data: orderData,\r\n");
      out.write("                options: { scales: { y: { beginAtZero: true, title: { display: true, text: 'Number of Orders' } } }, plugins: { legend: { display: false } } }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            const profitData = {\r\n");
      out.write("                labels: [\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"],\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    label: 'Profit ($)',\r\n");
      out.write("                    data: [");
 Map<String, Double> mp = (Map<String, Double>) request.getAttribute("monthlyProfit"); for (String m : new String[]{"January","February","March","April","May","June","July","August","September","October","November","December"}) { out.print(mp != null ? mp.getOrDefault(m, 0.0) : 0.0); out.print(","); } 
      out.write("],\r\n");
      out.write("                    backgroundColor: '#001f3f',\r\n");
      out.write("                    borderColor: '#001f3f',\r\n");
      out.write("                    fill: false,\r\n");
      out.write("                    tension: 0.1\r\n");
      out.write("                }]\r\n");
      out.write("            };\r\n");
      out.write("            new Chart(document.getElementById('profitChart'), {\r\n");
      out.write("                type: 'line',\r\n");
      out.write("                data: profitData,\r\n");
      out.write("                options: { scales: { y: { beginAtZero: true, title: { display: true, text: 'Profit ($)' } } }, plugins: { legend: { display: false } } }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
