/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-13 11:46:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.spareparts.model.Supplier;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.spareparts.model.Supplier");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Admin Dashboard - Full Trade Support</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap -->\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Tailwind CSS -->\r\n");
      out.write("  <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      font-family: Arial, sans-serif;\r\n");
      out.write("      background-color: #f8f9fa;\r\n");
      out.write("    }\r\n");
      out.write("    .sidebar {\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("      background-color: #0d6efd;\r\n");
      out.write("      color: white;\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      width: 240px;\r\n");
      out.write("      padding-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .sidebar a {\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      display: block;\r\n");
      out.write("      padding: 12px 20px;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("    .sidebar a:hover {\r\n");
      out.write("      background-color: #0b5ed7;\r\n");
      out.write("    }\r\n");
      out.write("    .main-content {\r\n");
      out.write("      margin-left: 240px;\r\n");
      out.write("    }\r\n");
      out.write("    .dashboard-content {\r\n");
      out.write("      padding: 40px;\r\n");
      out.write("      min-height: calc(100vh - 56px);\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Sidebar -->\r\n");
      out.write("  <div class=\"sidebar\">\r\n");
      out.write("    <h4 class=\"text-center mb-4\">Manager Panel</h4>\r\n");
      out.write("    <a href=\"#\"><i class=\"fas fa-users me-2\"></i>User Management</a>\r\n");
      out.write("    <a href=\"#\"><i class=\"fas fa-boxes me-2\"></i>Stock Management</a>\r\n");
      out.write("    <a href=\"#\"><i class=\"fas fa-shopping-cart me-2\"></i>Order Management</a>\r\n");
      out.write("    <a href=\"#\"><i class=\"fas fa-cash-register me-2\"></i>Cashier</a>\r\n");
      out.write("    <a href=\"#\"><i class=\"fas fa-box me-2\"></i>Item Management</a>\r\n");
      out.write("    <a href=\"#\"><i class=\"fas fa-user-friends me-2\"></i>Customer Management</a>\r\n");
      out.write("    <a href=\"#\"><i class=\"fas fa-truck me-2\"></i>Supplier Management</a>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Main Content -->\r\n");
      out.write("  <div class=\"main-content\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light px-4 bg-white shadow-sm\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">Full Trade Support</a>\r\n");
      out.write("      <div class=\"ms-auto d-flex align-items-center\">\r\n");
      out.write("        <span class=\"me-3\">Welcome, <strong>Manager</strong></span>\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("          <a class=\"btn btn-light dropdown-toggle\" href=\"#\" id=\"userDropdown\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("            <i class=\"fas fa-user-circle\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"userDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Profile</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Settings</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item text-danger\" href=\"#\">Logout</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"dashboard-content\">\r\n");
      out.write("      <h2 class=\"text-xl font-bold mb-4\">User Management</h2>\r\n");
      out.write("      <p class=\"mb-4 text-gray-600\">Manage your User below:</p>\r\n");
      out.write("\r\n");
      out.write("      ");

        String id = request.getParameter("id");
        String name = request.getParameter("name");
        String address = request.getParameter("address");
        String contactnumber = request.getParameter("contactnumber");
        String email = request.getParameter("email");
        String password = request.getParameter("password");
        String userRole = request.getParameter("userRole");
      
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"bg-white rounded-xl shadow-md p-6 max-w-2xl\">\r\n");
      out.write("        <h4 class=\"text-lg font-semibold mb-4 text-blue-600\">Update Supplier</h4>\r\n");
      out.write("        <form action=\"UpdateServlet\" method=\"post\" class=\"space-y-4\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <label class=\"form-label block mb-1 font-medium\">ID</label>\r\n");
      out.write("            <input type=\"text\" name=\"id\" value=\"");
      out.print( id );
      out.write("\" readonly\r\n");
      out.write("              class=\"form-control bg-gray-100 border border-gray-300 rounded px-3 py-2 w-full\" />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div>\r\n");
      out.write("            <label class=\"form-label block mb-1 font-medium\">Name</label>\r\n");
      out.write("            <input type=\"text\" name=\"name\" value=\"");
      out.print( name );
      out.write("\" required\r\n");
      out.write("              class=\"form-control border border-gray-300 rounded px-3 py-2 w-full\" />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div>\r\n");
      out.write("            <label class=\"form-label block mb-1 font-medium\">Address</label>\r\n");
      out.write("            <input type=\"text\" name=\"address\" value=\"");
      out.print( address );
      out.write("\" required\r\n");
      out.write("              class=\"form-control border border-gray-300 rounded px-3 py-2 w-full\" />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div>\r\n");
      out.write("            <label class=\"form-label block mb-1 font-medium\">Contact Number</label>\r\n");
      out.write("            <input type=\"text\" name=\"contactnumber\" value=\"");
      out.print( contactnumber );
      out.write("\" required\r\n");
      out.write("              class=\"form-control border border-gray-300 rounded px-3 py-2 w-full\" />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div>\r\n");
      out.write("            <label class=\"form-label block mb-1 font-medium\">Email</label>\r\n");
      out.write("            <input type=\"email\" name=\"email\" value=\"");
      out.print( email );
      out.write("\" required\r\n");
      out.write("              class=\"form-control border border-gray-300 rounded px-3 py-2 w-full\" />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div>\r\n");
      out.write("            <label class=\"form-label block mb-1 font-medium\">Password</label>\r\n");
      out.write("            <input type=\"text\" name=\"password\" value=\"");
      out.print( password );
      out.write("\" required\r\n");
      out.write("              class=\"form-control border border-gray-300 rounded px-3 py-2 w-full\" />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("      <div>\r\n");
      out.write("		  <label class=\"form-label block mb-1 font-medium\">User Role</label>\r\n");
      out.write("		  <select name=\"userRole\" class=\"form-control border border-gray-300 rounded px-3 py-2 w-full\" required>\r\n");
      out.write("		    <option value=\"Cashier\" ");
      out.print( "Cashier".equals(userRole) ? "selected" : "" );
      out.write(" >Cashier</option>\r\n");
      out.write("		    <option value=\"Stock Manager\" ");
      out.print( "Stock Manager".equals(userRole) ? "selected" : "" );
      out.write(">Stock Manager</option>\r\n");
      out.write("		    <option value=\"Admin\" ");
      out.print( "Admin".equals(userRole) ? "selected" : "" );
      out.write(">Admin</option>\r\n");
      out.write("		    <option value=\"Manager\" ");
      out.print( "Manager".equals(userRole) ? "selected" : "" );
      out.write(">Manager</option>\r\n");
      out.write("		  </select>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("          <div>\r\n");
      out.write("            <button type=\"submit\"\r\n");
      out.write("              class=\"btn btn-primary w-full bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded-lg transition\">\r\n");
      out.write("              Update User\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap JS -->\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
