/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-15 07:36:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.spareparts.model.DetailsModel;

public final class display_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/%20Spare_parts_Management_Systems/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1746542412270L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.spareparts.model.DetailsModel");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Full Trade Support Dashboard</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body { display: flex; min-height: 100vh; overflow-x: hidden; }\r\n");
      out.write("        .sidebar { width: 250px; background-color: #001f3f; color: #fff; flex-shrink: 0; padding-top: 1rem; }\r\n");
      out.write("        .sidebar a { display: block; padding: 12px 20px; color: #fff; text-decoration: none; transition: background 0.3s; }\r\n");
      out.write("        .sidebar a:hover { background-color: #003366; }\r\n");
      out.write("        .sidebar h5 { text-align: center; margin-bottom: 1rem; font-weight: bold; }\r\n");
      out.write("        .main-content { flex-grow: 1; background: #f8f9fa; }\r\n");
      out.write("        .navbar { background-color: #ffffff; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }\r\n");
      out.write("        .dashboard-content { padding: 2rem; }\r\n");
      out.write("        .custom-header { background-color: #0d0b56; color: white; }\r\n");
      out.write("        .btn-primary { background-color: #0d0b56; border-color: #0d0b56; }\r\n");
      out.write("        .btn-primary:hover { background-color: #003366; border-color: #003366; }\r\n");
      out.write("        .card { border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }\r\n");
      out.write("        .chart-container { max-width: 600px; margin: auto; }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("      ");
 String userRole = (String) session.getAttribute("userRole"); 
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"sidebar\">\r\n");
      out.write("        <h5 class=\"text-center fw-bold\">\r\n");
      out.write("            ");
      out.print( userRole != null ? userRole + " Panel" : "Panel" );
      out.write("\r\n");
      out.write("        </h5>\r\n");
      out.write("        ");
 if ("Manager".equals(userRole) || "Admin".equals(userRole)) { 
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\">\r\n");
      out.write("                <i class=\"fas fa-chart-line me-2\"></i> Dashboard\r\n");
      out.write("            </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cashier\">\r\n");
      out.write("            <i class=\"fas fa-cash-register me-2\"></i> Cashier\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 if ("Admin".equals(userRole) || "Manager".equals(userRole)) { 
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/GetAllServlet\">\r\n");
      out.write("                <i class=\"fas fa-users me-2\"></i> User Management\r\n");
      out.write("            </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (!"Cashier".equals(userRole)) { 
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/item-list\">\r\n");
      out.write("                <i class=\"fas fa-boxes me-2\"></i> Stock Management\r\n");
      out.write("            </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if ("Stock Manager".equals(userRole)) { 
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order-management\">\r\n");
      out.write("                <i class=\"fas fa-shopping-cart me-2\"></i> Order Management\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/item-list\">\r\n");
      out.write("                <i class=\"fas fa-box me-2\"></i> Item Management\r\n");
      out.write("            </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if ("Admin".equals(userRole) || "Manager".equals(userRole)) { 
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/supplier-list\">\r\n");
      out.write("                <i class=\"fas fa-truck me-2\"></i> Supplier Management\r\n");
      out.write("            </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <a href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#settingsMenu\">\r\n");
      out.write("            <i class=\"fas fa-gear me-2\"></i> Settings\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"collapse ms-3\" id=\"settingsMenu\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile.jsp\" class=\"d-block mt-1\">\r\n");
      out.write("                <i class=\"fas fa-sliders-h me-2\"></i> Profile\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-content w-100\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-white px-4 shadow-sm\">\r\n");
      out.write("            <a class=\"navbar-brand fw-bold\" href=\"#\">Autoparts Pvt Ltd</a>\r\n");
      out.write("            <div class=\"ms-auto d-flex align-items-center\">\r\n");
      out.write("                ");
      out.print( session.getAttribute("Name") != null ? session.getAttribute("Name") : "Guest" );
      out.write("\r\n");
      out.write("                <div class=\"dropdown ms-3\">\r\n");
      out.write("                    <a class=\"btn btn-light dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"fas fa-user-circle fa-lg\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile.jsp\"><i class=\"fas fa-id-badge me-2\"></i> Profile</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\"><i class=\"fas fa-sign-out-alt me-2\"></i> Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    <!-- User Management Section -->\r\n");
      out.write("    <div class=\"dashboard-content\">\r\n");
      out.write("      <h2>User Management</h2>\r\n");
      out.write("      <p>Manage system users below:</p>\r\n");
      out.write("\r\n");
      out.write("      <!-- Search Bar -->\r\n");
      out.write("      <div class=\"mb-3 w-100\">\r\n");
      out.write("        <div class=\"input-group shadow-sm\">\r\n");
      out.write("          <span class=\"input-group-text bg-white border-end-0\">\r\n");
      out.write("            <i class=\"fas fa-search text-secondary\"></i>\r\n");
      out.write("          </span>\r\n");
      out.write("          <input type=\"text\" id=\"searchInput\" class=\"form-control border-start-0\" placeholder=\"Search users...\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Export Buttons -->\r\n");
      out.write("      <div class=\"mb-3 d-flex gap-2\">\r\n");
      out.write("        <button onclick=\"exportTableToPDF()\" class=\"btn export-btn\">\r\n");
      out.write("          <i class=\"fas fa-file-pdf me-1\"></i> Export PDF\r\n");
      out.write("        </button>\r\n");
      out.write("        <button onclick=\"exportTableToExcel()\" class=\"btn export-btn\">\r\n");
      out.write("          <i class=\"fas fa-file-excel me-1\"></i> Export Excel\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Add Button -->\r\n");
      out.write("		 <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Admin/insert.jsp\" class=\"btn btn-primary mb-3\">\r\n");
      out.write("		  <i class=\"fas fa-user-plus me-1\"></i> Add New User\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- User Table -->\r\n");
      out.write("      <div class=\"table-container mt-4\">\r\n");
      out.write("        <table class=\"table table-bordered table-striped\" id=\"user-table\">\r\n");
      out.write("          <thead class=\"custom-header\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th>ID</th>\r\n");
      out.write("              <th>Name</th>\r\n");
      out.write("              <th>Address</th>\r\n");
      out.write("              <th>Contact Number</th>\r\n");
      out.write("              <th>User Role</th>\r\n");
      out.write("              <th>Action</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </thead>\r\n");
      out.write("          <tbody>\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("          </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS Scripts -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      function filterTable() {\r\n");
      out.write("        const input = document.getElementById(\"searchInput\");\r\n");
      out.write("        const filter = input.value.toUpperCase();\r\n");
      out.write("        const table = document.querySelector(\"#user-table\");\r\n");
      out.write("        const rows = table.getElementsByTagName(\"tr\");\r\n");
      out.write("\r\n");
      out.write("        for (let i = 1; i < rows.length; i++) {\r\n");
      out.write("          let rowVisible = false;\r\n");
      out.write("          const cells = rows[i].getElementsByTagName(\"td\");\r\n");
      out.write("\r\n");
      out.write("          for (let j = 0; j < cells.length - 1; j++) {\r\n");
      out.write("            if (cells[j]) {\r\n");
      out.write("              const text = cells[j].textContent || cells[j].innerText;\r\n");
      out.write("              if (text.toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("                rowVisible = true;\r\n");
      out.write("                break;\r\n");
      out.write("              }\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("          rows[i].style.display = rowVisible ? \"\" : \"none\";\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      document.getElementById(\"searchInput\").addEventListener(\"input\", filterTable);\r\n");
      out.write("\r\n");
      out.write("      async function exportTableToPDF() {\r\n");
      out.write("        const { jsPDF } = window.jspdf;\r\n");
      out.write("        const doc = new jsPDF();\r\n");
      out.write("\r\n");
      out.write("        const table = document.getElementById('user-table');\r\n");
      out.write("        const headers = [];\r\n");
      out.write("        const data = [];\r\n");
      out.write("\r\n");
      out.write("        const headerCells = table.querySelectorAll('thead tr th');\r\n");
      out.write("        headerCells.forEach((th, index) => {\r\n");
      out.write("          if (index < headerCells.length - 1) {\r\n");
      out.write("            headers.push(th.innerText.trim());\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        const rows = table.querySelectorAll('tbody tr');\r\n");
      out.write("        rows.forEach(row => {\r\n");
      out.write("          const rowData = [];\r\n");
      out.write("          const cells = row.querySelectorAll('td');\r\n");
      out.write("          cells.forEach((td, index) => {\r\n");
      out.write("            if (index < cells.length - 1) {\r\n");
      out.write("              rowData.push(td.innerText.trim());\r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("          if (rowData.length > 0) {\r\n");
      out.write("            data.push(rowData);\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        doc.autoTable({\r\n");
      out.write("          head: [headers],\r\n");
      out.write("          body: data,\r\n");
      out.write("          theme: 'grid',\r\n");
      out.write("          headStyles: { fillColor: [13, 11, 86] },\r\n");
      out.write("          styles: { fontSize: 9 }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        doc.save('user_details.pdf');\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function exportTableToExcel() {\r\n");
      out.write("        var table = document.getElementById('user-table');\r\n");
      out.write("        var wb = XLSX.utils.table_to_book(table, { sheet: \"Suppliers\" });\r\n");
      out.write("        XLSX.writeFile(wb, 'supplier_data.xlsx');\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.23/jspdf.plugin.autotable.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /Admin/display.jsp(138,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("details");
    // /Admin/display.jsp(138,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Admin/display.jsp(138,12) '${alldetails}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${alldetails}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("              <tr>\r\n");
          out.write("                <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.contactnumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.userRole}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                <td>\r\n");
          out.write("                  <div class=\"d-flex gap-2\">\r\n");
          out.write("                    <a href=\"Admin/update.jsp?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&name=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&address=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&contactnumber=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.contactnumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&email=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&password=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&userRole=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.userRole}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn btn-primary btn-sm\">\r\n");
          out.write("                      <i class=\"fas fa-edit\"></i>\r\n");
          out.write("                    </a>\r\n");
          out.write("                    <a href=\"DeleteServlet?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${details.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn btn-outline-danger btn-sm\" onclick=\"return confirm('Are you sure?')\">\r\n");
          out.write("                      <i class=\"fas fa-trash-alt\"></i>\r\n");
          out.write("                    </a>\r\n");
          out.write("                  </div>\r\n");
          out.write("                </td>\r\n");
          out.write("              </tr>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
